### ISSUE TITLE
Potential bug about FancyMenu layouts not loading after updating to Drippy v2.X.X [NOT CONFIRMED]

### ISSUE THREAD

**Issue by PanoptesDreams** [Keksuccino/Drippy-Loading-Screen#37]
You made Fancy Menu a required dependency and all my shit's gone.

Just merge the two projects because at this point it no longer makes sense to separate them, especially considering FancyMenu is a dependency.

**Comment by Keksuccino** [comment]
Dude I can do what the **fuck** I want and if I want to separate two projects to not have to search 200 classes every time I need to fix something in Drippy, then I will do exactly that.

Your sHiT iS gOnE because you updated to a new version that is incompatible with old layouts, which is exactly what it tells you when you launch the game for the first time after updating the mod, but I bet you just clicked away the popup without reading it.

As you successfully observed: Yes, you can simply downgrade the mod to use your old layouts.

**Comment by Keksuccino** [comment]
_Deleted my old answer because of my inappropriate language and to add more information about why I don't want to merge both mods. Sorry for that, but you kinda triggered me._


### I will not merge Drippy and FancyMenu. Why? Well..

1. Debugging is a lot easier if you have two separate mods and a user tells you something like "it happens when I have Drippy installed". Now I know that I have to search in Drippy and don't need to search the ~200 classes of FancyMenu.
2. Drippy heavily modifies the loading screen and by doing that, it obviously also modifies the vanilla game loading behaviour, which is kind of a big thing, because it can break everything if you combine it with an incompatible mod. Yes, I could use a config option in FancyMenu to disable all loading screen modifications, but modpack devs don't want to change dozens of mod configs to search for incompatibilities. They just want to disable some mods, see if the incompatibility is fixed and if yes, check that small mod bundle for the bad one.
3. It's a lot easier for me to find stuff in my code when not everything is in one big mod. Being able to quickly tell what Mixins are exclusively for Drippy, for example, is just a great little thing I don't want to miss.

If you don't like the new version, that's fine, just keep using the old one, but if you want to continue using Drippy in 1.19.4+, you will need to update, because I will not port the old 1.X.X version to newer MC versions, I'm very sorry.


### To the "shit's gone" thing:

Because you were not really clear about what "all my shit's gone" is referring to, I assumed you were talking about your old Drippy layouts not loading anymore, which is indeed correct, you will need to remake them. The mod tells you that when you open the game for the first time after updating to any Drippy v2.X.X build.
But after reading the issue you openend in FancyMenu's repository, I think you mean literally **all** of your stuff is not working anymore, including **FancyMenu layouts**? In that case it's **probably a mod conflict** and you will need to find the mod that's breaking Drippy, because Drippy v2.X.X works fine for many other people, including me.

**Comment by Keksuccino** [comment]
Closed because no response and not reproducible.
