### ISSUE TITLE
DLS + Fancy Menu = No DLS config button

### ISSUE THREAD

**Issue by LynxarA-Coding** [Keksuccino/Drippy-Loading-Screen#56]
**Description**
If the menu is already edited and the DLS mod was downloaded after, than Fancy Menu doesn't show DLS config button anymore

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Make a custom GUI and make it default (override)
2. Install Drippy Loading screen mod
3. Launch Minecraft
4. No error on loading, no DLS button in the main menu

**Expected behavior**
A DLS settings button

**Game Log**
[latest.log](https://github.com/Keksuccino/Drippy-Loading-Screen/files/11591453/latest.log)

**Basic Informations:**
 - OS: Windows 11
 - Drippy Version: latest (2.2.1)
 - Forge/Fabric Version: 40.2.4
 - Minecraft Version 1.18.2
 - Active Mods: none except Drippy + Fancy + Ice and Fire + 80 more
 The Ice and Fire main menu is disabled

**Comment by Keksuccino** [comment]
By custom GUI and "override", do you literally mean overriding the Title Screen with a custom GUI or do you just make a layout for the Title Screen? Because yeah well, if you override the GUI, you will obviously don't have the Drippy button anymore, because you completely replaced the original menu.

But if you talk about a layout, then you probably just disabled the customization overlay (the little menu bar at the top of menus). Drippy's button will be hidden too if you hide the overlay, so just press **CTRL + ALT + C** (by default) to make it visible again.

**Comment by LynxarA-Coding** [comment]
Editing default layout with Ice and Fire is impossible I think due to it forcing the background to a custom one.
With the clear head tried to do it all over again and figured it out. I will leave the fix in this message in case someone googles an issue.

1. Go to your configs
2. Locate `iceandfire-client.toml`
3. Change "Custom main menu" to false
4. Reset Fancy Menu config (by deleting `fancymenu` folder inside `config`) if you tried to make a Custom GUI or Layout already
5. Launch Minecraft

**Comment by Keksuccino** [comment]
https://fm.keksuccino.dev/en/incompatibility-list

I'm happy you were able to figure it out! :)
